name: Build Nebula APK

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Get version
        run: echo "VERSION=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Build web
        run: pnpm build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate Icon & Splash Screen Native
        run: npx @capacitor/assets generate --android

      - name: Install Capacitor CLI
        run: pnpm exec cap sync android

      - name: Decode Keystore
        if: github.ref == 'refs/heads/main'
        working-directory: android
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 --decode > nebula-release.jks

      - name: Build APK Release
        if: github.ref == 'refs/heads/main'
        working-directory: android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/nebula-release.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_PASSWORD }}

          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Nebula-${{ env.VERSION }}.apk

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Nebula ${{ env.VERSION }}
          files: android/app/build/outputs/apk/release/Nebula-${{ env.VERSION }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build APK Debug
        if: github.ref == 'refs/heads/dev'
        working-directory: android
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Nebula_${{ env.VERSION }}-debug.apk

      - name: Upload APK Debug
        if: github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: nebula_${{ env.VERSION }}-debug-apk
          path: android/app/build/outputs/apk/debug/Nebula_${{ env.VERSION }}-debug.apk
          retention-days: 7
